apiVersion: v1
kind: Namespace
metadata:
  name: dps-system
  labels:
    app.kubernetes.io/name: deep-parallel-synthesis
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dps-resource-quota
  namespace: dps-system
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 50Gi
    requests.nvidia.com/gpu: "4"
    limits.cpu: "40"
    limits.memory: 100Gi
    limits.nvidia.com/gpu: "4"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dps-limit-range
  namespace: dps-system
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "8"
      memory: "16Gi"
    type: Container